name: ML Pipeline

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow dvc scikit-learn pandas

      - name: Pull data
        run: dvc pull || echo "No DVC repo – skipped"

      - name: Train model
        run: python train.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: model_info
          path: model_info.txt

  deploy:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: model_info

      - name: Check threshold
        run: python check_threshold.py

      - name: Build Docker Image
        run: |
          docker build --build-arg RUN_ID=$(cat model_info.txt) -t mymodel:latest .
