name: ML Pipeline

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5  # تحديث النسخة لتجنب Node.js 20

      - name: Install dependencies
        run: pip install mlflow dvc

      - name: Pull data
        run: dvc pull || echo "No DVC repo"

      - name: Train model
        run: python train.py

      - name: Save Run ID
        run: echo "run_12345" > model_info.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3  # تحديث النسخة
        with:
          name: model_info
          path: model_info.txt

  deploy:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5  # تحديث النسخة

      - name: Download artifact
        uses: actions/download-artifact@v3  # تحديث النسخة
        with:
          name: model_info

      - name: Check threshold
        run: python check_threshold.py

      - name: Mock Docker Build
        run: |
          echo "Building Docker image for Run ID: $(cat model_info.txt)"
